### ISSUE TITLE
[Comment] Thanks for the post on errors

### ISSUE THREAD

**Issue by saona-raimundo** [SabrinaJewson/sabrinajewson.github.io#1]
Hi!

This is a fellow Rustacean.
I just wanted to tell you that I enjoyed your [post on errors](https://sabrinajewson.org/blog/errors) very much.
I saw it in "This Week in Rust 490".

Thanks again!

(Feel free to close the issue)

**Comment by SabrinaJewson** [comment]
Thanks, I’m glad you enjoyed it <3
