### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by vanilla-extracts** [SabrinaJewson/sabrinajewson.github.io#5]
Hello, 
I stumbled onto your website and loved it!
When I read your article on how you built it I almost implemented a similar thing myself, but I decided to fork the repository to use for my writing website (https://github.com/coco33920/writing-website) 

The main question I have is what is the license of your code? Of course, I credited you in the footer (you can see it at https://writing.nwa2coco.fr) but I wanted to know what the exact license was. Because if it is a copyright all right reserved I need to close my website and re-implement the Rust code myself without breaking your copyright.

Thanks,
Cheers,
Charlotte Thomas.

**Comment by SabrinaJewson** [comment]
Good point, I haven’t thought about this :sweat_smile: 

I’ll add it to the repo later, but let’s say everything is `MIT OR Apache-2.0`

**Comment by vanilla-extracts** [comment]
Ok noted 👍
Thank you, I skimmed through the code and it's very elegant.
